receivers:
    otlp:
        protocols:
            grpc:

processors:
    batch:

exporters:
    otlp/jaeger:
        endpoint: jaeger:4317
        tls:
            insecure: true

    debug:

extensions:
    health_check:
    zpages:

service:
    extensions: [zpages, health_check]
    telemetry:
        logs:
            level: debug
        metrics:
            level: normal
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/jaeger]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug]
